### Resources

Paper based on this work: https://arxiv.org/pdf/1912.10133.pdf
Input files for this work: https://osf.io/kbn5a/
Tutorials and tests on using larcv: https://github.com/DeepLearnPhysics/larcv3/tree/develop/tests


In [2]:
import larcv
import numpy

In [3]:
io = larcv.IOManager()

In [4]:
io.add_in_file("merged_sample_0.h5")

In [5]:
io.initialize()

    [NORMAL]  <IOManager::prepare_input> Opening a file in READ mode: "merged_sample_0.h5"
    [NORMAL]  <IOManager::prepare_input> File "merged_sample_0.h5" has 1404 entries
    [NORMAL]  <IOManager::initialize> Prepared input with 1404 entries...


True

In [6]:
voxel_counts = numpy.zeros((io.get_n_entries(),3))

In [7]:
print(voxel_counts)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import h5py,itertools
import array
import matplotlib.pyplot as plt

In [9]:
fname = "merged_sample_0.h5"

def printname(name):
    print(name)

   
with h5py.File(fname,'r') as f:
    f.visit(printname)


Data
Data/cluster2d_duneseg_group
Data/cluster2d_duneseg_group/cluster_extents
Data/cluster2d_duneseg_group/extents
Data/cluster2d_duneseg_group/image_meta
Data/cluster2d_duneseg_group/projection_extents
Data/cluster2d_duneseg_group/voxels
Data/cluster2d_segment_group
Data/cluster2d_segment_group/cluster_extents
Data/cluster2d_segment_group/extents
Data/cluster2d_segment_group/image_meta
Data/cluster2d_segment_group/projection_extents
Data/cluster2d_segment_group/voxels
Data/cluster3d_segment_group
Data/cluster3d_segment_group/cluster_extents
Data/cluster3d_segment_group/extents
Data/cluster3d_segment_group/image_meta
Data/cluster3d_segment_group/projection_extents
Data/cluster3d_segment_group/voxels
Data/particle_all_group
Data/particle_all_group/extents
Data/particle_all_group/particles
Data/particle_cpiID_group
Data/particle_cpiID_group/extents
Data/particle_cpiID_group/particles
Data/particle_duneseg_group
Data/particle_duneseg_group/extents
Data/particle_duneseg_group/particles
Da

## Content
We want to see what is inside these hdf5 files. 
## Data
Data group has 13 subgroups.
Events group has 1 data-set.

In [10]:
data = "Data"
evts = "Events"
dat_list=[]
evt_list=[]
with h5py.File(fname,'r') as f:
    print("Keys: %s "% f.keys())
    cand = list(f.keys())
    dat_list = list(f["Data"])
    evt_list = list(f["Events"])
    
print(len(dat_list))
print("--------------------")
print(len(evt_list),evt_list)


Keys: <KeysViewHDF5 ['Data', 'Events']> 
13
--------------------
1 ['event_id']


In [11]:
evt_id = []
with h5py.File(fname,'r') as f:
    event = f["Events"]
    print(type(event)) #Events is a group
    evt_id = event["event_id"][:]
    

<class 'h5py._hl.group.Group'>


In [12]:
#Lets look at the content of few data-sets...
sparse3d_dunevoxels_group = {}
sparse2d_dunevoxels_group ={}

[None]


In [28]:
dsets = {}
dat_keys = []
with h5py.File(fname,'r') as f:
    dat_group = f["Data"]
    dat_keys = f["Data"].keys()
    for key in dat_keys:
        if "sparse3d" in key:
            dat_subgroup = dat_group[key]
            dat_dkeys = dat_subgroup.keys()
            for subkey in dat_dkeys:
                dsets[key+"_"+subkey] = dat_subgroup[subkey][:]
        
        

In [29]:
print(dsets)

{'sparse3d_dunevoxels_group_extents': array([(   0, 1), (   1, 1), (   2, 1), ..., (1401, 1), (1402, 1),
       (1403, 1)], dtype=[('first', '<u4'), ('N', '<u4')]), 'sparse3d_dunevoxels_group_image_meta': array([(1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.]),
       (1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.]),
       (1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.]),
       ...,
       (1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.]),
       (1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.]),
       (1, 0, [360., 200., 500.], [ 900,  500, 1250], [   0., -100.,    0.])],
      dtype={'names': ['valid', 'projection_id', 'image_sizes', 'number_of_voxels', 'origin'], 'formats': ['u1', '<u8', ('<f8', (3,)), ('<u8', (3,)), ('<f8', (3,))], 'offsets': [0, 8, 16, 40, 64], 'itemsize': 96}), 'sparse3d_dunevoxels_group_voxel_extents': array([(      0,   222, 0), (    222,  1971, 0), (   219

In [37]:
import numpy as np
voxels3D = np.array(dsets["sparse3d_dunevoxels_group_voxels"])

In [38]:
image_meta = np.array(dsets["sparse3d_dunevoxels_group_image_meta"])

In [39]:
print(len(image_meta))

1404


In [41]:
print(voxels3D.shape,image_meta.shape)


(2800337,) (1404,)


In [48]:
for i in range(0,5):
    print(voxels3D[i])

(74319916, 7.8222356)
(74944916, 2.9229536)
(74946166, 10.390908)
(75571166, 8.832149)
(76196166, 6.517799)


### Below we test the larcv related functionalities


In [49]:
voxel = numpy.zeros((io.get_n_entries(),1))

In [53]:
print(len(voxel),voxel.shape)

1404 (1404, 1)


In [55]:
print(voxel[0],voxel[1])

[0.] [0.]


In [56]:
tot_entries = io.get_n_entries()

In [72]:
voxel_counts3d = numpy.zeros((io.get_n_entries(),1))
mean = []
rms = []
for i in range(tot_entries):
    io.read_entry(i)
    image3d = io.get_data("sparse3d","dunevoxels")
    voxel_counts3d[i] = image3d.as_vector()[0].size()
    if i%100 ==0:
        print("On entry ",i,tot_entries)
    print(" 3D: {av:.2f} +/- {rms:.2f} ({max} max)".format(
        av  = numpy.mean(voxel_counts3d[:]), 
        rms = numpy.std(voxel_counts3d[:]), 
        max = numpy.max(voxel_counts3d[:])
        )
    )
     

On entry  0 1404
 3D: 0.16 +/- 5.92 (222.0 max)
 3D: 1.56 +/- 52.91 (1971.0 max)
 3D: 2.16 +/- 57.49 (1971.0 max)
 3D: 2.26 +/- 57.59 (1971.0 max)
 3D: 4.54 +/- 102.97 (3202.0 max)
 3D: 5.59 +/- 110.23 (3202.0 max)
 3D: 8.63 +/- 158.28 (4263.0 max)
 3D: 9.01 +/- 158.90 (4263.0 max)
 3D: 10.15 +/- 164.47 (4263.0 max)
 3D: 10.73 +/- 165.86 (4263.0 max)
 3D: 11.26 +/- 167.01 (4263.0 max)
 3D: 14.06 +/- 197.05 (4263.0 max)
 3D: 14.74 +/- 198.66 (4263.0 max)
 3D: 15.38 +/- 200.06 (4263.0 max)
 3D: 16.58 +/- 204.95 (4263.0 max)
 3D: 19.86 +/- 238.69 (4603.0 max)
 3D: 24.88 +/- 303.61 (7053.0 max)
 3D: 25.02 +/- 303.65 (7053.0 max)
 3D: 25.12 +/- 303.66 (7053.0 max)
 3D: 25.21 +/- 303.67 (7053.0 max)
 3D: 25.71 +/- 304.21 (7053.0 max)
 3D: 27.53 +/- 311.54 (7053.0 max)
 3D: 30.46 +/- 330.14 (7053.0 max)
 3D: 31.23 +/- 331.33 (7053.0 max)
 3D: 31.38 +/- 331.36 (7053.0 max)
 3D: 34.97 +/- 357.29 (7053.0 max)
 3D: 35.48 +/- 357.74 (7053.0 max)
 3D: 37.31 +/- 364.09 (7053.0 max)
 3D: 38.22 +/- 36

 3D: 833.27 +/- 2124.40 (23182.0 max)
 3D: 834.11 +/- 2124.30 (23182.0 max)
 3D: 837.04 +/- 2125.99 (23182.0 max)
 3D: 837.25 +/- 2125.92 (23182.0 max)
 3D: 837.99 +/- 2125.81 (23182.0 max)
 3D: 847.31 +/- 2150.68 (23182.0 max)
 3D: 854.03 +/- 2162.74 (23182.0 max)
 3D: 854.15 +/- 2162.70 (23182.0 max)
 3D: 854.85 +/- 2162.58 (23182.0 max)
 3D: 854.96 +/- 2162.54 (23182.0 max)
 3D: 855.12 +/- 2162.49 (23182.0 max)
 3D: 855.55 +/- 2162.38 (23182.0 max)
 3D: 863.40 +/- 2179.19 (23182.0 max)
 3D: 865.98 +/- 2180.32 (23182.0 max)
 3D: 867.58 +/- 2180.50 (23182.0 max)
 3D: 868.43 +/- 2180.40 (23182.0 max)
 3D: 869.28 +/- 2180.29 (23182.0 max)
 3D: 871.08 +/- 2180.61 (23182.0 max)
 3D: 871.94 +/- 2180.51 (23182.0 max)
 3D: 875.16 +/- 2182.54 (23182.0 max)
 3D: 878.88 +/- 2185.51 (23182.0 max)
 3D: 884.50 +/- 2193.37 (23182.0 max)
 3D: 884.67 +/- 2193.31 (23182.0 max)
 3D: 885.11 +/- 2193.20 (23182.0 max)
 3D: 892.05 +/- 2205.73 (23182.0 max)
 3D: 892.10 +/- 2205.72 (23182.0 max)
 3D: 892.79 

 3D: 1804.18 +/- 2909.56 (26606.0 max)
 3D: 1804.34 +/- 2909.46 (26606.0 max)
 3D: 1804.89 +/- 2909.19 (26606.0 max)
 3D: 1806.26 +/- 2908.80 (26606.0 max)
 3D: 1807.76 +/- 2908.41 (26606.0 max)
 3D: 1808.46 +/- 2908.09 (26606.0 max)
 3D: 1808.52 +/- 2908.06 (26606.0 max)
 3D: 1809.63 +/- 2907.66 (26606.0 max)
 3D: 1811.20 +/- 2907.28 (26606.0 max)
 3D: 1814.09 +/- 2907.50 (26606.0 max)
 3D: 1816.16 +/- 2907.24 (26606.0 max)
 3D: 1817.39 +/- 2906.83 (26606.0 max)
 3D: 1818.22 +/- 2906.48 (26606.0 max)
 3D: 1818.50 +/- 2906.33 (26606.0 max)
 3D: 1819.24 +/- 2906.00 (26606.0 max)
 3D: 1819.62 +/- 2905.79 (26606.0 max)
 3D: 1819.71 +/- 2905.74 (26606.0 max)
 3D: 1819.96 +/- 2905.59 (26606.0 max)
 3D: 1820.35 +/- 2905.39 (26606.0 max)
 3D: 1820.43 +/- 2905.34 (26606.0 max)
 3D: 1821.38 +/- 2904.96 (26606.0 max)
 3D: 1822.17 +/- 2904.62 (26606.0 max)
 3D: 1822.42 +/- 2904.47 (26606.0 max)
 3D: 1829.93 +/- 2913.35 (26606.0 max)
On entry  1300 1404
 3D: 1830.18 +/- 2913.20 (26606.0 max)
 3D: 

In [62]:
io.read_entry(0)
dat = io.get_data("sparse3d","dunevoxels")

In [63]:
print(dat)

### Does not seems to have functions:
larcv.EventSparseTensor3D.to_sparse_tensor
Just use image = io.get_data("sparse3d","dunevoxels")